services:
  minio:
    image: 'minio/minio:RELEASE.2024-01-31T20-20-33Z'

    ports:
      - '19000:9000'
      - '19001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

volumes:
  minio-data:
    driver: local
