name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install package in dev mode
        run: pip install -e .

      - name: Install test requirements
        run: pip install -r requirements_test.txt

      - name: Build
        run: ./build.sh
        env:
          TERM: xterm-256color
