name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"

      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
          version: "0.8.x"

      - name: Install the project
        run: make install
        env:
          TERM: xterm-256color

      - name: Run the build
        run: make build
        env:
          TERM: xterm-256color
