name: publish
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"

      - name: Publish to pypi
        run: make dist && make dist/release
        env:
          TERM: xterm-256color
